const media=[
  {id:'neon-city',title:'Neon City Pack',type:'PHOTO',price:'$6.99'},
  {id:'motion-set',title:'Creator Motion Set',type:'VIDEO',price:'$12.99'},
  {id:'travel-stories',title:'Travel Stories',type:'PHOTO',price:'$8.50'},
  {id:'cinematic-reels',title:'Cinematic Reels',type:'VIDEO',price:'$15.00'}
];
const creators=[['AR','Aria Rose','128 items'],['MK','Miko','84 items'],['LV','Livia','211 items']];
const grid=document.getElementById('trendingGrid'),creatorRow=document.getElementById('creatorRow'),main=document.getElementById('mainContent'),modal=document.getElementById('modal'),modalCard=document.getElementById('modalCard');
const read=(k,f=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f)),write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const purchases=()=>read('veloraPurchases'),follows=()=>read('veloraFollows'),listings=()=>read('veloraListings',[{id:'mine-1',title:'Pink Neon Portraits',type:'PHOTO',price:'$9.99',status:'Published',sales:18},{id:'mine-2',title:'Night Motion Reel',type:'VIDEO',price:'$14.00',status:'Published',sales:11}]);
const profile=()=>read('veloraProfile',{name:'VELORA Creator',bio:'Creator demo profile'});
let deferredInstallPrompt=null;
function closeModal(){modal.classList.add('hidden')} window.closeModal=closeModal; modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function setActive(name){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===name))}
function page(title,body){main.innerHTML=`<section class="section" style="margin-top:24px"><div class="section-head"><h2>${title}</h2></div>${body}</section>`}
function mediaCard(m){return `<button class="media-card" data-product="${m.id}"><span class="pill">${m.type}</span><h3>${m.title}</h3><div class="price">${m.price}</div></button>`}
function bindProductCards(){document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>openProduct(media.find(m=>m.id===el.dataset.product)||listings().find(m=>m.id===el.dataset.product)))}
function creatorCard(c){const following=follows().includes(c[1]);return `<div class="creator"><div class="creator-head"><div class="avatar">${c[0]}</div><span class="muted">★ 4.9</span></div><strong>${c[1]}</strong><small>${c[2]}</small><button class="follow-btn ${following?'following':''}" data-follow="${c[1]}">${following?'Following':'Follow'}</button></div>`}
function bindFollowButtons(){document.querySelectorAll('[data-follow]').forEach(btn=>btn.onclick=()=>{const name=btn.dataset.follow;let cur=follows();cur=cur.includes(name)?cur.filter(x=>x!==name):[...cur,name];write('veloraFollows',cur);btn.classList.toggle('following',cur.includes(name));btn.textContent=cur.includes(name)?'Following':'Follow'})}
function renderInitial(){media.forEach(m=>{const c=document.createElement('button');c.className='media-card';c.dataset.product=m.id;c.innerHTML=`<span class="pill">${m.type}</span><h3>${m.title}</h3><div class="price">${m.price}</div>`;grid.appendChild(c)});bindProductCards();creatorRow.innerHTML=creators.map(creatorCard).join('');bindFollowButtons()}
function addPurchase(id){const item=media.find(m=>m.id===id)||listings().find(m=>m.id===id);if(!item)return;const cur=purchases();if(!cur.some(x=>x.id===id))write('veloraPurchases',[...cur,item]);modalCard.innerHTML=`<h2>Added to Purchases</h2><p class="muted">${item.title} is now saved in your demo library.</p><button class="btn primary" style="width:100%" onclick="closeModal();navigate('purchases')">View Purchases</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Continue Browsing</button>`} window.addPurchase=addPurchase;
function openProduct(m){if(!m)return;modalCard.innerHTML=`<div class="pill">${m.type}</div><h2 style="margin-top:12px">${m.title}</h2><p class="muted">Premium creator asset • Instant access demo</p><div class="product-preview"></div><div class="product-meta"><div><span>Demo price</span><strong>${m.price}</strong></div><div><span>Rating</span><strong>★ 4.9</strong></div></div><button class="btn primary" style="width:100%" onclick="addPurchase('${m.id}')">Add to Purchases</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden')}
function renderExplore(type='ALL'){const shown=type==='ALL'?media:media.filter(m=>m.type===type);page('Explore',`<div class="tabs"><button class="tab ${type==='ALL'?'active':''}" data-filter="ALL">All</button><button class="tab ${type==='PHOTO'?'active':''}" data-filter="PHOTO">Photos</button><button class="tab ${type==='VIDEO'?'active':''}" data-filter="VIDEO">Videos</button></div><div class="media-grid">${shown.map(mediaCard).join('')}</div>`);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>renderExplore(b.dataset.filter));bindProductCards()}
function renderPurchases(){const items=purchases();page('Purchases',items.length?`<div class="demo-note">Demo library • Items are stored locally on this device.</div><div class="media-grid" style="margin-top:14px">${items.map(mediaCard).join('')}</div><button class="btn ghost" id="clearPurchases" style="width:100%;margin-top:16px">Clear Demo Purchases</button>`:`<div class="profile-panel"><div class="avatar">V</div><h3>No purchases yet</h3><p class="muted">Explore VELORA and add a demo item to see it here.</p><button class="btn primary" onclick="navigate('explore')">Explore Marketplace</button></div>`);bindProductCards();const clear=document.getElementById('clearPurchases');if(clear)clear.onclick=()=>{write('veloraPurchases',[]);renderPurchases()}}
function renderUpload(){page('Upload & Sell',`<div class="upload-zone"><div class="upload-arrow">↑</div><strong>Create a demo listing</strong><span>Choose a photo or video from your device</span></div><label>Title</label><input class="field" id="uploadTitle" placeholder="Name your content"><label>Type</label><select class="field" id="uploadType"><option>PHOTO</option><option>VIDEO</option></select><label>Price</label><input class="field" id="uploadPrice" placeholder="$9.99"><label>File</label><input class="field" id="uploadFile" type="file" accept="image/*,video/*"><button class="btn primary" id="publishBtn" style="width:100%">Publish Demo Listing</button><div class="demo-note">Demo only: the selected file stays on your device.</div>`);document.getElementById('publishBtn').onclick=()=>{const title=document.getElementById('uploadTitle').value.trim(),type=document.getElementById('uploadType').value,price=document.getElementById('uploadPrice').value.trim()||'$9.99';if(!title)return alert('Please enter a title.');const cur=listings(),item={id:'mine-'+Date.now(),title,type,price,status:'Published',sales:0};write('veloraListings',[item,...cur]);modalCard.innerHTML=`<h2>Listing published</h2><div class="product-preview"></div><p class="muted"><strong style="color:#fff">${title}</strong> was added to My Listings.</p><button class="btn primary" style="width:100%" onclick="closeModal();renderDashboard()">Open Seller Dashboard</button>`;modal.classList.remove('hidden')}}
function renderDashboard(){setActive('profile');const mine=listings(),totalSales=mine.reduce((s,x)=>s+(x.sales||0),0);page('Seller Dashboard',`<div class="earnings-card"><small>ESTIMATED DEMO EARNINGS</small><strong>$128.40</strong><span>+ $18.70 this week</span></div><div class="dashboard-grid"><button class="dash-card" id="earningsBtn"><strong>$128.40</strong><span>Earnings</span></button><button class="dash-card" id="salesBtn"><strong>${totalSales}</strong><span>Total sales</span></button><button class="dash-card" id="listingsBtn"><strong>${mine.length}</strong><span>My listings</span></button><button class="dash-card" onclick="navigate('upload')"><strong>＋</strong><span>New listing</span></button></div><div class="section-head inner-head"><h3>Recent listings</h3><button class="text-btn" id="viewListings">View all</button></div><div class="listing-list">${mine.slice(0,3).map(listingRow).join('')}</div>`);document.getElementById('earningsBtn').onclick=renderEarnings;document.getElementById('salesBtn').onclick=renderEarnings;document.getElementById('listingsBtn').onclick=renderListings;document.getElementById('viewListings').onclick=renderListings}
window.renderDashboard=renderDashboard;
function listingRow(x){return `<div class="listing-row"><div class="listing-thumb">${x.type==='VIDEO'?'▶':'▧'}</div><div class="listing-info"><strong>${x.title}</strong><span>${x.status} • ${x.sales||0} sales</span></div><div class="listing-price">${x.price}</div></div>`}
function renderListings(){page('My Listings',`<div class="listing-list">${listings().map(listingRow).join('')}</div><button class="btn primary" style="width:100%;margin-top:16px" onclick="navigate('upload')">Create New Listing</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="renderDashboard()">Back to Dashboard</button>`)}
function renderEarnings(){page('Earnings',`<div class="earnings-card big"><small>DEMO BALANCE</small><strong>$128.40</strong><span>Not connected to real funds</span></div><div class="earning-line"><span>This week</span><strong>$18.70</strong></div><div class="earning-line"><span>This month</span><strong>$74.20</strong></div><div class="earning-line"><span>All time</span><strong>$128.40</strong></div><div class="demo-note">Demo analytics only. Payment processing and withdrawals are not connected.</div><button class="btn ghost" style="width:100%;margin-top:14px" onclick="renderDashboard()">Back to Dashboard</button>`)}
function editProfile(){const p=profile();modalCard.innerHTML=`<h2>Edit Profile</h2><label>Display name</label><input class="field" id="editName" value="${p.name}"><label>Bio</label><input class="field" id="editBio" value="${p.bio}"><button class="btn primary" id="saveProfile" style="width:100%">Save Demo Profile</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Cancel</button>`;modal.classList.remove('hidden');document.getElementById('saveProfile').onclick=()=>{write('veloraProfile',{name:document.getElementById('editName').value.trim()||'VELORA Creator',bio:document.getElementById('editBio').value.trim()||'Creator demo profile'});closeModal();renderProfile()}}
function renderProfile(){const p=profile(),followed=follows().length;page('Profile',`<div class="profile-panel"><div class="avatar">V</div><h2 style="margin:0">${p.name}</h2><p class="muted">${p.bio}</p><div class="wallet-card"><div class="wallet-row"><div><small>DEMO BALANCE</small><strong>$128.40</strong><small>Available earnings</small></div><button class="mini-btn" id="dashboardBtn">Dashboard</button></div></div><div class="stats-grid"><div class="stat-card"><strong>${listings().length}</strong><small>ITEMS</small></div><div class="stat-card"><strong>1.8K</strong><small>FOLLOWERS</small></div><div class="stat-card"><strong>${followed}</strong><small>FOLLOWING</small></div></div><button class="btn primary" id="editProfileBtn" style="width:100%">Edit Profile</button><button class="btn ghost" id="loginBtn" style="width:100%;margin-top:10px">Login / Register</button><button class="install-chip" id="installBtn">Install VELORA App</button></div>`);document.getElementById('dashboardBtn').onclick=renderDashboard;document.getElementById('editProfileBtn').onclick=editProfile;document.getElementById('loginBtn').onclick=()=>{modalCard.innerHTML=`<h2>Login to VELORA</h2><p class="muted">Demo sign-in screen</p><input class="field" placeholder="Email"><input class="field" type="password" placeholder="Password"><button class="btn primary" style="width:100%" onclick="alert('Demo login only')">Continue</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden')};document.getElementById('installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}else alert('Use your browser menu and choose Add to Home screen / Install app.')}}
function navigate(name){setActive(name);if(name==='home')return location.reload();if(name==='explore')return renderExplore();if(name==='upload')return renderUpload();if(name==='purchases')return renderPurchases();if(name==='profile')return renderProfile()}
window.navigate=navigate;document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
document.getElementById('searchBtn').onclick=()=>{modalCard.innerHTML=`<h2>Search VELORA</h2><input class="field" id="searchInput" autofocus placeholder="Search photos, videos, creators"><button class="btn primary" id="doSearch" style="width:100%">Search</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden');document.getElementById('doSearch').onclick=()=>{const q=document.getElementById('searchInput').value.trim().toLowerCase(),found=media.filter(m=>m.title.toLowerCase().includes(q)||m.type.toLowerCase().includes(q));modalCard.innerHTML=`<h2>Search Results</h2>${found.length?`<div class="media-grid">${found.map(mediaCard).join('')}</div>`:`<div class="empty">No results found.</div>`}<button class="btn ghost" style="width:100%;margin-top:14px" onclick="closeModal()">Close</button>`;bindProductCards()}};
document.getElementById('notifyBtn').onclick=()=>{document.getElementById('notifyBtn').classList.add('seen');modalCard.innerHTML=`<h2>Notifications</h2><div class="notification-item"><strong>New sale</strong><span>Night Motion Reel received a demo sale.</span></div><div class="notification-item"><strong>Earnings update</strong><span>Your demo balance increased this week.</span></div><div class="notification-item"><strong>Tip</strong><span>Open Seller Dashboard from Profile to manage listings.</span></div><button class="btn ghost" style="width:100%;margin-top:14px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));renderInitial();