const media=[
  {id:'neon-city',title:'Neon City Pack',type:'PHOTO',price:'$6.99'},
  {id:'motion-set',title:'Creator Motion Set',type:'VIDEO',price:'$12.99'},
  {id:'travel-stories',title:'Travel Stories',type:'PHOTO',price:'$8.50'},
  {id:'cinematic-reels',title:'Cinematic Reels',type:'VIDEO',price:'$15.00'}
];
const creators=[['AR','Aria Rose','128 items'],['MK','Miko','84 items'],['LV','Livia','211 items']];
const grid=document.getElementById('trendingGrid');
const creatorRow=document.getElementById('creatorRow');
const main=document.getElementById('mainContent');
const modal=document.getElementById('modal');
const modalCard=document.getElementById('modalCard');
const purchases=()=>JSON.parse(localStorage.getItem('veloraPurchases')||'[]');
const savePurchases=(items)=>localStorage.setItem('veloraPurchases',JSON.stringify(items));

function renderHome(){location.reload()}
function closeModal(){modal.classList.add('hidden')}
window.closeModal=closeModal;
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function setActive(name){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===name))}
function page(title,body){main.innerHTML=`<section class="section" style="margin-top:24px"><div class="section-head"><h2>${title}</h2></div>${body}</section>`}
function mediaCard(m){return `<button class="media-card" data-product="${m.id}"><span class="pill">${m.type}</span><h3>${m.title}</h3><div class="price">${m.price}</div></button>`}
function bindProductCards(){document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>openProduct(media.find(m=>m.id===el.dataset.product)))}
function renderInitial(){media.forEach(m=>{const c=document.createElement('button');c.className='media-card';c.dataset.product=m.id;c.innerHTML=`<span class="pill">${m.type}</span><h3>${m.title}</h3><div class="price">${m.price}</div>`;grid.appendChild(c)});bindProductCards();creators.forEach(c=>{const el=document.createElement('div');el.className='creator';el.innerHTML=`<div class="avatar">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small>`;creatorRow.appendChild(el)})}
function addPurchase(id){const item=media.find(m=>m.id===id);if(!item)return;const current=purchases();if(!current.some(x=>x.id===id)){current.push(item);savePurchases(current)};modalCard.innerHTML=`<h2>Added to Purchases</h2><p class="muted">${item.title} is now saved in your demo library.</p><button class="btn primary" style="width:100%" onclick="closeModal();navigate('purchases')">View Purchases</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Continue Browsing</button>`}
window.addPurchase=addPurchase;
function openProduct(m){modalCard.innerHTML=`<div class="pill">${m.type}</div><h2 style="margin-top:12px">${m.title}</h2><p class="muted">Premium creator asset • Instant access demo</p><div class="product-preview"></div><div style="display:flex;align-items:end;justify-content:space-between;margin:12px 0 16px"><div><div class="muted">Demo price</div><h2 style="margin:2px 0 0">${m.price}</h2></div><div class="muted">★ 4.9</div></div><button class="btn primary" style="width:100%" onclick="addPurchase('${m.id}')">Add to Purchases</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden')}
function renderExplore(type='ALL'){const shown=type==='ALL'?media:media.filter(m=>m.type===type);page('Explore',`<div class="tabs"><button class="tab ${type==='ALL'?'active':''}" data-filter="ALL">All</button><button class="tab ${type==='PHOTO'?'active':''}" data-filter="PHOTO">Photos</button><button class="tab ${type==='VIDEO'?'active':''}" data-filter="VIDEO">Videos</button></div><div class="media-grid">${shown.map(mediaCard).join('')}</div>`);document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>renderExplore(b.dataset.filter));bindProductCards()}
function renderPurchases(){const items=purchases();page('Purchases',items.length?`<div class="demo-note">Demo library • Items are stored locally on this device.</div><div class="media-grid" style="margin-top:14px">${items.map(mediaCard).join('')}</div><button class="btn ghost" id="clearPurchases" style="width:100%;margin-top:16px">Clear Demo Purchases</button>`:`<div class="profile-panel"><div class="avatar">V</div><h3>No purchases yet</h3><p class="muted">Explore VELORA and add a demo item to see it here.</p><button class="btn primary" onclick="navigate('explore')">Explore Marketplace</button></div>`);bindProductCards();const clear=document.getElementById('clearPurchases');if(clear)clear.onclick=()=>{savePurchases([]);renderPurchases()}}
function renderUpload(){page('Upload & Sell',`<div class="upload-zone"><div style="font-size:28px">↑</div><strong>Create a demo listing</strong><span>Choose a photo or video from your device</span></div><label>Title</label><input class="field" id="uploadTitle" placeholder="Name your content"><label>Type</label><select class="field" id="uploadType"><option>Photo</option><option>Video</option></select><label>Price</label><input class="field" id="uploadPrice" placeholder="$0.00"><label>File</label><input class="field" id="uploadFile" type="file" accept="image/*,video/*"><button class="btn primary" id="publishBtn" style="width:100%">Publish Demo Listing</button><div class="demo-note">Demo only: the selected file stays on your device. Server upload and payments are not connected yet.</div>`);document.getElementById('publishBtn').onclick=()=>{const title=document.getElementById('uploadTitle').value.trim();if(!title){alert('Please enter a title.');return}modalCard.innerHTML=`<h2>Listing ready</h2><div class="product-preview"></div><p class="muted"><strong style="color:#fff">${title}</strong> is prepared as a demo listing.</p><button class="btn primary" style="width:100%" onclick="closeModal();navigate('profile')">View Creator Profile</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Done</button>`;modal.classList.remove('hidden')}}
function renderProfile(){page('Profile',`<div class="profile-panel"><div class="avatar">V</div><h2 style="margin:0">VELORA Creator</h2><p class="muted">Creator demo profile</p><div class="stats-grid"><div class="stat-card"><strong>24</strong><small>ITEMS</small></div><div class="stat-card"><strong>1.8K</strong><small>FOLLOWERS</small></div><div class="stat-card"><strong>4.9</strong><small>RATING</small></div></div><button class="btn primary" id="loginBtn" style="width:100%">Login / Register</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="navigate('upload')">Create Listing</button></div>`);document.getElementById('loginBtn').onclick=()=>{modalCard.innerHTML=`<h2>Login to VELORA</h2><p class="muted">Demo sign-in screen</p><input class="field" placeholder="Email"><input class="field" type="password" placeholder="Password"><button class="btn primary" style="width:100%" onclick="alert('Demo login only')">Continue</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden')}}
function navigate(name){setActive(name);if(name==='home')return renderHome();if(name==='explore')return renderExplore();if(name==='upload')return renderUpload();if(name==='purchases')return renderPurchases();if(name==='profile')return renderProfile()}
window.navigate=navigate;
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
document.getElementById('searchBtn').onclick=()=>{modalCard.innerHTML=`<h2>Search VELORA</h2><input class="field" id="searchInput" autofocus placeholder="Search photos, videos, creators"><button class="btn primary" id="doSearch" style="width:100%">Search</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeModal()">Close</button>`;modal.classList.remove('hidden');document.getElementById('doSearch').onclick=()=>{const q=document.getElementById('searchInput').value.trim().toLowerCase();const found=media.filter(m=>m.title.toLowerCase().includes(q)||m.type.toLowerCase().includes(q));modalCard.innerHTML=`<h2>Search Results</h2>${found.length?`<div class="media-grid">${found.map(mediaCard).join('')}</div>`:`<div class="empty">No results found.</div>`}<button class="btn ghost" style="width:100%;margin-top:14px" onclick="closeModal()">Close</button>`;bindProductCards()}};
renderInitial();
