// VELORA Prompt & Image Marketplace layer
const promptCatalog=[
{id:'mountain-lake',title:'Mountain Lake Reflection',type:'PROMPT + IMAGE',price:'$2.50',creator:'Aurora Vision',sales:'1.2K',category:'Photography',prompt:'A breathtaking mountain landscape at sunset, crystal clear lake with perfect reflection, a wooden cabin by the lake with warm lights, pine trees, dramatic orange and pink clouds, ultra realistic, highly detailed, 8k, photo realistic.',negative:'blurry, low quality, text, watermark, logo, extra limbs, disfigured, deformed, bad anatomy'},
{id:'cozy-cafe',title:'Cozy Cafe Evening',type:'PROMPT + IMAGE',price:'$1.90',creator:'Pixel Nomad',sales:'896',category:'Photography',prompt:'Cozy cinematic cafe at evening, warm amber lights, rainy street reflections, detailed storefront, realistic photography, soft depth of field.',negative:'blurry, low resolution, watermark, text, distorted perspective'},
{id:'anime-girl',title:'Anime Girl Portrait',type:'PROMPT + IMAGE',price:'$2.20',creator:'Luna AI',sales:'1.5K',category:'Anime',prompt:'Elegant anime girl portrait, soft pastel lighting, detailed eyes and hair, cinematic background, polished illustration, high detail.',negative:'bad anatomy, extra fingers, blurry, low quality, watermark'},
{id:'cyber-city',title:'Cyberpunk City Night',type:'PROMPT + IMAGE',price:'$3.00',creator:'DreamScape',sales:'732',category:'3D / Render',prompt:'Futuristic cyberpunk city at night, neon lights, tall skyscrapers, flying cars, wet streets, reflections, cinematic, ultra detailed, 8k, octane render.',negative:'blurry, low quality, text, watermark, logo, extra limbs, bad anatomy'}
];
function promptCard(m){const fav=wishlist().includes(m.id);return `<button class="media-card" data-prompt="${m.id}"><span class="pill">${m.price}</span><span class="fav-mark">${fav?'♥':'♡'}</span><h3>${m.title}</h3><small style="font-size:9px;color:#aab3bf">by ${m.creator}</small></button>`}
function bindPromptCards(){document.querySelectorAll('[data-prompt]').forEach(el=>el.onclick=()=>openPrompt(promptCatalog.find(x=>x.id===el.dataset.prompt)))}
function renderInitial(){if(grid){grid.innerHTML=promptCatalog.slice(0,3).map(promptCard).join('');bindPromptCards()}if(creatorRow){creatorRow.innerHTML=[['AV','Aurora Vision','1.2K Sales'],['PN','Pixel Nomad','896 Sales'],['LA','Luna AI','1.5K Sales'],['DS','DreamScape','732 Sales']].map(c=>`<div class="creator"><div class="creator-head"><div class="avatar">${c[0]}</div></div><strong>${c[1]}</strong><small>${c[2]}</small></div>`).join('')}}
function openPrompt(m){if(!m)return;const fav=wishlist().includes(m.id);modalCard.innerHTML=`<div class="product-preview prompt-image"></div><div style="display:flex;justify-content:space-between;gap:10px"><div><h2 style="margin:0">${m.title}</h2><p class="muted">by ${m.creator} • ${m.sales} Sales</p></div><h2 style="color:#ff337f;margin:0">${m.price}</h2></div><div class="include-box"><strong>What's Included</strong><span>✓ High quality AI image (JPG)</span><span>✓ Commercial License</span><span>✓ Detailed Prompt</span><span>✓ Negative Prompt</span></div><div class="prompt-label"><strong>Prompt</strong><button onclick="copyPrompt('${m.id}','prompt')">Copy</button></div><div class="prompt-box">${m.prompt}</div><div class="prompt-label"><strong>Negative Prompt</strong><button onclick="copyPrompt('${m.id}','negative')">Copy</button></div><div class="prompt-box">${m.negative}</div><div class="dual-actions"><button class="btn ghost" onclick="togglePromptFavorite('${m.id}')">${fav?'♥ Saved':'♡ Add to Favorites'}</button><button class="btn primary" onclick="buyPrompt('${m.id}')">Buy Now ${m.price}</button></div>`;modal.classList.remove('hidden')}
window.openPrompt=openPrompt;
function copyPrompt(id,key){const m=promptCatalog.find(x=>x.id===id);if(m&&navigator.clipboard)navigator.clipboard.writeText(m[key]);alert('Copied')};window.copyPrompt=copyPrompt;
function togglePromptFavorite(id){let cur=wishlist();cur=cur.includes(id)?cur.filter(x=>x!==id):[...cur,id];write('veloraWishlist',cur);openPrompt(promptCatalog.find(x=>x.id===id))};window.togglePromptFavorite=togglePromptFavorite;
function buyPrompt(id){const m=promptCatalog.find(x=>x.id===id);if(!m)return;let p=purchases();if(!p.some(x=>x.id===id))write('veloraPurchases',[...p,m]);const order={id:'VL'+Date.now().toString().slice(-7),title:m.title,price:m.price,date:new Date().toLocaleDateString(),status:'Completed'};write('veloraOrders',[order,...orders()]);modalCard.innerHTML=`<div class="success-badge">✓</div><h2>Purchase Complete</h2><p class="muted">${m.title} is now in your library.</p><button class="btn primary" style="width:100%" onclick="closeModal();renderPurchases()">Open Library</button>`};window.buyPrompt=buyPrompt;
function renderExplore(cat='ALL'){setActive('explore');const shown=cat==='ALL'?promptCatalog:promptCatalog.filter(x=>x.category===cat);page('Explore Prompts',`<div class="tabs"><button class="tab ${cat==='ALL'?'active':''}" data-pcat="ALL">All</button><button class="tab ${cat==='Photography'?'active':''}" data-pcat="Photography">Photo</button><button class="tab ${cat==='Anime'?'active':''}" data-pcat="Anime">Anime</button></div><div class="media-grid">${shown.map(promptCard).join('')}</div>`);document.querySelectorAll('[data-pcat]').forEach(b=>b.onclick=()=>renderExplore(b.dataset.pcat));bindPromptCards()}
function renderPurchases(){setActive('purchases');const saved=promptCatalog.filter(x=>wishlist().includes(x.id));page('Favorites',saved.length?`<div class="media-grid">${saved.map(promptCard).join('')}</div><button class="btn ghost" style="width:100%;margin-top:16px" onclick="renderLibrary()">Purchased Library</button>`:`<div class="empty-panel"><div class="empty-icon">♡</div><h3>No favorites yet</h3><p>Save prompts you like and they will appear here.</p></div><button class="btn ghost" style="width:100%;margin-top:16px" onclick="renderLibrary()">Purchased Library</button>`);bindPromptCards()}
function renderLibrary(){const ids=purchases().map(x=>x.id),items=promptCatalog.filter(x=>ids.includes(x.id));page('Purchased Library',items.length?`<div class="media-grid">${items.map(promptCard).join('')}</div>`:`<div class="empty-panel"><h3>No purchases yet</h3><p>Your purchased images and prompts will appear here.</p></div>`);bindPromptCards()};window.renderLibrary=renderLibrary;
function renderUpload(){setActive('upload');page('Sell Your Prompt & Image',`<p class="muted">Share your AI generated image and prompt with others and earn money.</p><div class="upload-zone"><div class="upload-arrow">＋</div><strong>Add Cover Image</strong><span>Up to 6 images</span></div><label>Title</label><input class="field" id="uploadTitle" placeholder="Cyberpunk City Night"><label>Category</label><select class="field" id="uploadType"><option>Photography</option><option>Illustration</option><option>3D / Render</option><option>Anime</option><option>UI / UX</option></select><label>Description</label><textarea class="field" id="uploadDesc" rows="3" placeholder="Describe your image..."></textarea><label>Price (USD)</label><input class="field" id="uploadPrice" placeholder="3.00"><label>License Type</label><select class="field"><option>Commercial</option><option>Editorial</option></select><label>Prompt</label><textarea class="field" id="uploadPrompt" rows="5" placeholder="Enter the full image prompt"></textarea><label>Negative Prompt (optional)</label><textarea class="field" id="uploadNegative" rows="3" placeholder="blurry, low quality..."></textarea><label>Image</label><input class="field" type="file" accept="image/*"><button class="btn primary" id="publishBtn" style="width:100%">Publish Listing</button>`);document.getElementById('publishBtn').onclick=()=>{const title=document.getElementById('uploadTitle').value.trim(),prompt=document.getElementById('uploadPrompt').value.trim();if(!title||!prompt)return alert('Please add a title and prompt.');modalCard.innerHTML=`<div class="success-badge">✓</div><h2>Listing Published</h2><p class="muted">${title} has been added to your listings.</p><button class="btn primary" style="width:100%" onclick="closeModal();renderProfile()">View Profile</button>`;modal.classList.remove('hidden')}}
function renderProfile(){setActive('profile');page('Profile',`<div class="profile-panel"><div class="avatar">V</div><h2>VELORA Creator</h2><p class="muted">Prompt & Image Seller</p><div class="earnings-card"><small>TOTAL EARNINGS</small><strong>$1,248.50</strong><span>312 Sales • 586 Downloads</span></div><div class="dashboard-grid"><button class="dash-card" onclick="renderUpload()"><strong>＋</strong><span>Upload New</span></button><button class="dash-card"><strong>312</strong><span>Sales</span></button><button class="dash-card"><strong>586</strong><span>Downloads</span></button><button class="dash-card" onclick="renderLibrary()"><strong>▣</strong><span>Orders</span></button></div></div>`)}
window.renderExplore=renderExplore;window.renderPurchases=renderPurchases;window.renderUpload=renderUpload;window.renderProfile=renderProfile;
setTimeout(renderInitial,0);
