const seedCatalog=[
{id:'mountain-lake',title:'Mountain Lake Reflection',category:'Photography',price:'$2.50',creator:'Aurora Vision',sales:'1.2K',prompt:'A breathtaking mountain landscape at sunset, crystal clear lake with perfect reflection, a wooden cabin by the lake with warm lights, pine trees, dramatic orange and pink clouds, ultra realistic, highly detailed, 8k, photo realistic.',negative:'blurry, low quality, text, watermark, logo, extra limbs, disfigured, deformed, bad anatomy'},
{id:'cozy-cafe',title:'Cozy Cafe Evening',category:'Photography',price:'$1.90',creator:'Pixel Nomad',sales:'896',prompt:'Cozy cinematic cafe at evening, warm amber lights, rainy street reflections, detailed storefront, realistic photography, soft depth of field.',negative:'blurry, low resolution, watermark, text, distorted perspective'},
{id:'anime-girl',title:'Anime Girl Portrait',category:'Anime',price:'$2.20',creator:'Luna AI',sales:'1.5K',prompt:'Elegant anime girl portrait, soft pastel lighting, detailed eyes and hair, cinematic background, polished illustration, high detail.',negative:'bad anatomy, extra fingers, blurry, low quality, watermark'},
{id:'cyber-city',title:'Cyberpunk City Night',category:'3D / Render',price:'$3.00',creator:'DreamScape',sales:'732',prompt:'Futuristic cyberpunk city at night, neon lights, tall skyscrapers, flying cars, wet streets, reflections, cinematic, ultra detailed, 8k, octane render.',negative:'blurry, low quality, text, watermark, logo, extra limbs, bad anatomy'},
{id:'luxury-ui',title:'Luxury Mobile UI',category:'UI / UX',price:'$2.80',creator:'Nova Studio',sales:'641',prompt:'Premium mobile dashboard UI, dark glass interface, pink and violet neon accents, high-end typography, elegant rounded cards, polished UX presentation.',negative:'messy layout, blurry text, low contrast, distorted interface'},
{id:'storybook',title:'Dream Storybook Art',category:'Illustration',price:'$2.10',creator:'Mira Draws',sales:'508',prompt:'Whimsical storybook illustration, glowing forest path, soft magical lighting, detailed painted textures, dreamy atmosphere, premium editorial artwork.',negative:'photorealistic, blurry, watermark, low quality'}
];
const creators=[['AV','Aurora Vision','1.2K Sales'],['PN','Pixel Nomad','896 Sales'],['LA','Luna AI','1.5K Sales'],['DS','DreamScape','732 Sales'],['NS','Nova Studio','641 Sales']];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const home=$('#homePage'),dynamic=$('#dynamicPage'),sheet=$('#sheet'),sheetCard=$('#sheetCard');
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const favorites=()=>read('veloraFavorites',[]),purchases=()=>read('veloraPurchases',[]),listings=()=>read('veloraSellerListings',[]);
const normalizePrice=v=>{const n=Number(String(v).replace('$',''));return Number.isFinite(n)?`$${n.toFixed(2)}`:'$3.00'};
function sellerCatalog(){return listings().map((x,i)=>({id:x.id||`seller-${i}`,title:x.title||'Untitled',category:x.category||'Photography',price:normalizePrice(x.price),creator:'VELORA Creator',sales:String(x.sales||0),prompt:x.prompt||'',negative:x.negative||'',description:x.description||'',seller:true}))}
function catalog(){return [...sellerCatalog(),...seedCatalog]}
function promptCard(m){const fav=favorites().includes(m.id);return `<button class="prompt-card" data-product="${m.id}"><div class="prompt-thumb ${m.category.replace(/\W/g,'').toLowerCase()}"></div><span class="price-pill">${m.price}</span><span class="heart-pill">${fav?'♥':'♡'} ${m.sales||0}</span><div class="prompt-info"><h3>${m.title}</h3><div class="creator-mini">by ${m.creator}</div></div></button>`}
function bindCards(){$$('[data-product]').forEach(x=>x.onclick=()=>openProduct(x.dataset.product))}
function fillHome(){const all=catalog();$('#popularGrid').innerHTML=all.slice(0,3).map(promptCard).join('');$('#newGrid').innerHTML=all.slice(3,6).map(promptCard).join('');$('#creatorRow').innerHTML=creators.map(c=>`<div class="creator-card"><div class="creator-avatar">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small></div>`).join('');bindCards()}
function closeSheet(){sheet.classList.add('hidden')} window.closeSheet=closeSheet; sheet.onclick=e=>{if(e.target===sheet)closeSheet()};
async function copyText(text){try{await navigator.clipboard.writeText(text);alert('Copied')}catch{alert(text)}}
function toggleFavorite(id){let f=favorites();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];write('veloraFavorites',f);openProduct(id);fillHome()} window.toggleFavorite=toggleFavorite;
function openProduct(id){const m=catalog().find(x=>x.id===id);if(!m)return;const fav=favorites().includes(id),owned=purchases().includes(id)||m.seller;const promptArea=owned?`<div class="prompt-label"><strong>Prompt</strong><button id="copyPrompt">Copy</button></div><div class="prompt-box">${m.prompt||'No prompt added.'}</div><div class="prompt-label"><strong>Negative Prompt</strong><button id="copyNegative">Copy</button></div><div class="prompt-box">${m.negative||'None'}</div>`:`<div class="locked-prompt"><b>🔒 Prompt locked</b><span>Purchase this item to unlock and copy the full prompt.</span></div>`;sheetCard.innerHTML=`<button class="back-btn" onclick="closeSheet()">←</button><div class="hero-preview"></div><div class="product-top"><div><h2>${m.title}</h2><p class="muted">by ${m.creator} • ${m.sales||0} Sales • ★ 4.9</p></div><div class="product-price">${m.price}</div></div><div class="include-box"><strong>What's Included</strong><span>✓ High quality image</span><span>✓ Commercial usage details</span><span>✓ Detailed Prompt</span><span>✓ Negative Prompt</span></div>${promptArea}<div class="dual-actions"><button class="btn ghost" onclick="toggleFavorite('${id}')">${fav?'♥ Saved':'♡ Add to Favorites'}</button>${owned?`<button class="btn primary" onclick="alert('This item is already unlocked')">Unlocked ✓</button>`:`<button class="btn primary" id="buyNow">Buy Now ${m.price}</button>`}</div>`;sheet.classList.remove('hidden');if(owned){$('#copyPrompt').onclick=()=>copyText(m.prompt||'');$('#copyNegative').onclick=()=>copyText(m.negative||'None')}else $('#buyNow').onclick=()=>purchase(id)}
function purchase(id){const m=catalog().find(x=>x.id===id);if(!m)return;let p=purchases();if(!p.includes(id))write('veloraPurchases',[...p,id]);sheetCard.innerHTML=`<div class="empty-panel"><div class="success-check">✓</div><h2>Purchase Complete</h2><p class="muted">${m.title} is now unlocked in your library.</p><button class="btn primary" style="width:100%;margin-top:12px" onclick="openProduct('${id}')">View Image & Prompt</button><button class="btn ghost" style="width:100%;margin-top:10px" onclick="closeSheet();route('profile')">Open Profile</button></div>`}
function setNav(name){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.route===name))}
function showDynamic(html){home.classList.add('hidden');dynamic.classList.remove('hidden');dynamic.innerHTML=html;window.scrollTo(0,0)}
function route(name){setNav(name);if(name==='home'){dynamic.classList.add('hidden');home.classList.remove('hidden');fillHome();window.scrollTo(0,0);return}if(name==='explore')renderExplore();if(name==='sell')renderSell();if(name==='favorites')renderFavorites();if(name==='profile')renderProfile()} window.route=route;
function renderExplore(category='ALL'){const all=catalog(),shown=category==='ALL'?all:all.filter(x=>x.category===category);showDynamic(`<div class="dynamic-head"><button class="back-btn" onclick="route('home')">←</button><h2>Explore Prompts</h2></div><button class="search-box" id="exploreSearch"><b>⌕</b><span>Search all listings...</span></button><div class="category-strip">${['ALL','Photography','Illustration','3D / Render','Anime','UI / UX'].map(c=>`<button class="category ${c===category?'active':''}" data-filter="${c}"><i>${c==='ALL'?'✿':'◇'}</i><span>${c}</span></button>`).join('')}</div><div class="prompt-grid">${shown.map(promptCard).join('')}</div>`);$$('[data-filter]').forEach(b=>b.onclick=()=>renderExplore(b.dataset.filter));$('#exploreSearch').onclick=openSearch;bindCards()}
function renderFavorites(){const ids=favorites(),items=catalog().filter(x=>ids.includes(x.id));showDynamic(`<div class="dynamic-head"><button class="back-btn" onclick="route('home')">←</button><h2>Favorites</h2></div>${items.length?`<div class="prompt-grid">${items.map(promptCard).join('')}</div>`:`<div class="empty-panel"><h3>No favorites yet</h3><p class="muted">Save images and prompts you like.</p><button class="btn primary" onclick="route('explore')">Explore Marketplace</button></div>`}`);bindCards()}
function renderSell(){showDynamic(`<div class="dynamic-head"><button class="back-btn" onclick="route('home')">←</button><h2>Sell Your Prompt & Image</h2></div><p class="muted">Add your image, exact prompt and selling price.</p><label class="upload-zone" id="uploadZone"><div><b>＋</b><strong style="display:block;margin-top:7px">Add Cover Image</strong><span class="muted">JPG or PNG</span></div><input id="sellFile" type="file" accept="image/*" hidden></label><div id="imagePreview" class="sell-preview hidden"></div><label>Title</label><input class="field" id="sellTitle" placeholder="Cyberpunk City Night"><label>Category</label><select class="field" id="sellCategory"><option>Photography</option><option>Illustration</option><option>3D / Render</option><option>Anime</option><option>UI / UX</option></select><label>Description</label><textarea class="field" id="sellDesc" rows="3" placeholder="Describe your image..."></textarea><div class="form-row"><div><label>Price (USD)</label><input class="field" id="sellPrice" inputmode="decimal" placeholder="3.00"></div><div><label>License</label><select class="field" id="sellLicense"><option>Commercial</option><option>Editorial</option></select></div></div><label>Prompt</label><textarea class="field" id="sellPrompt" rows="5" placeholder="Enter the full prompt used to create the image"></textarea><label>Negative Prompt</label><textarea class="field" id="sellNegative" rows="3" placeholder="Optional"></textarea><button class="btn primary" id="publishListing" style="width:100%">Publish Listing</button>`);$('#sellFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const preview=$('#imagePreview');preview.style.backgroundImage=`url(${URL.createObjectURL(f)})`;preview.classList.remove('hidden')};$('#publishListing').onclick=()=>{const title=$('#sellTitle').value.trim(),prompt=$('#sellPrompt').value.trim();if(!title||!prompt)return alert('Please enter a title and prompt.');const item={id:'seller-'+Date.now(),title,category:$('#sellCategory').value,description:$('#sellDesc').value.trim(),price:$('#sellPrice').value.trim()||'3.00',license:$('#sellLicense').value,prompt,negative:$('#sellNegative').value.trim(),sales:0};write('veloraSellerListings',[item,...listings()]);fillHome();renderProfile()}}
function renderProfile(){const owned=catalog().filter(x=>purchases().includes(x.id)),mine=sellerCatalog();showDynamic(`<div class="dynamic-head"><button class="back-btn" onclick="route('home')">←</button><h2>Profile</h2></div><div class="profile-card"><div class="creator-avatar" style="margin:0">V</div><h2>VELORA Creator</h2><p class="muted">Image & Prompt Seller</p><div class="earnings-card"><small>TOTAL EARNINGS</small><strong>$1,248.50</strong><span>312 Sales • 586 Downloads</span></div><div class="dashboard-grid"><button class="dash-card" onclick="route('sell')"><strong>＋</strong><span>Upload New</span></button><div class="dash-card"><strong>${mine.length}</strong><span>My Listings</span></div><div class="dash-card"><strong>312</strong><span>Sales</span></div><div class="dash-card"><strong>${owned.length}</strong><span>Purchased</span></div></div></div>${mine.length?`<section class="content-section"><div class="section-head"><h2>My Listings</h2></div><div class="prompt-grid">${mine.map(promptCard).join('')}</div></section>`:''}<section class="content-section"><div class="section-head"><h2>Purchased Library</h2></div>${owned.length?`<div class="prompt-grid">${owned.map(promptCard).join('')}</div>`:`<div class="empty-panel"><p class="muted">Purchased images and prompts will appear here.</p></div>`}</section>`);bindCards()}
function openSearch(){sheetCard.innerHTML=`<h2>Search VELORA</h2><input class="field" id="searchInput" autofocus placeholder="Search prompts, styles, creators"><div class="search-results" id="searchResults"></div><button class="btn ghost" style="width:100%;margin-top:12px" onclick="closeSheet()">Close</button>`;sheet.classList.remove('hidden');const input=$('#searchInput'),results=$('#searchResults');const draw=()=>{const q=input.value.trim().toLowerCase(),found=q?catalog().filter(x=>[x.title,x.category,x.creator].some(v=>String(v).toLowerCase().includes(q))):catalog().slice(0,5);results.innerHTML=found.map(x=>`<button class="result-row" data-search-id="${x.id}"><div class="result-thumb"></div><div><strong>${x.title}</strong><small>${x.creator} • ${x.category}</small></div><b>${x.price}</b></button>`).join('');$$('[data-search-id]').forEach(b=>b.onclick=()=>openProduct(b.dataset.searchId))};input.oninput=draw;draw()}
$('#searchBtn').onclick=openSearch;$('#notifyBtn').onclick=()=>{sheetCard.innerHTML=`<h2>Notifications</h2><div class="result-row"><div>✦</div><div><strong>New creator upload</strong><small>Fresh image + prompt listings are available.</small></div></div><div class="result-row" style="margin-top:8px"><div>♡</div><div><strong>Favorites update</strong><small>Save products to revisit them later.</small></div></div><button class="btn ghost" style="width:100%;margin-top:14px" onclick="closeSheet()">Close</button>`;sheet.classList.remove('hidden')};
$('#menuBtn').onclick=()=>{sheetCard.innerHTML=`<h2>VELORA</h2><button class="menu-row" onclick="closeSheet();route('explore')">Explore Marketplace <b>›</b></button><button class="menu-row" onclick="closeSheet();route('sell')">Upload & Sell <b>›</b></button><button class="menu-row" onclick="closeSheet();route('favorites')">Favorites <b>›</b></button><button class="menu-row" onclick="closeSheet();route('profile')">Profile <b>›</b></button><button class="btn ghost" style="width:100%;margin-top:14px" onclick="closeSheet()">Close</button>`;sheet.classList.remove('hidden')};
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));
$$('#categoryStrip [data-category]').forEach(b=>b.onclick=()=>renderExplore(b.dataset.category));
fillHome();